volumes:
  pg-data:

services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - 'pg-data:/var/lib/postgresql/data:rw'
      - '../../libs/db/schema.d:/docker-entrypoint-initdb.d:ro'
  snapshotd:
    build:
      context: ../..
      dockerfile: deploy.d/Dockerfile
      args:
        COMPONENT: snapshotd
    environment:
      HN_API_CONCURRENCY: 50
      DB: 'host=pg port=5432 user=dev password=dev dbname=dev'
      RUST_LOG: 'info,playground=debug,take_snapshot=trace,hn_api=info'
    entrypoint: /app/bin/snapshotd
    
    