volumes:
  pg-data:

services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    volumes:
      - 'pg-data:/var/lib/postgresql/data:rw'
      - '../../libs/db/schema.d:/docker-entrypoint-initdb.d:ro'
  snapshots:
    build:
      context: ../..
      dockerfile: deploy.d/Dockerfile
      args:
        COMPONENT: take-snapshot
    environment:
      HN_API_CONCURRENCY: 50
      DB: 'host=pg port=5432 user=dev password=dev dbname=dev'
      RUST_LOG: 'info,playground=debug,take_snapshot=trace,hn_api=info'
    volumes:
      - '../../deploy.d/scripts.d/take-snapshots-periodically.sh:/app/sbin/take-snapshots-periodically.sh:ro'
    entrypoint: /app/sbin/take-snapshots-periodically.sh
    
    